version: version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./authelia/config:/config
    expose:
      - 9091
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.mydomain.com`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=myresolver"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./ib-backend/
    volumes:
      - ./ib-backend:/app
      - /app/target
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`mydomain.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.middlewares=authelia@docker"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./inkblink
    volumes:
      - ./inkblink:/app
      - /app/node_modules
    expose:
      - 5173
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mydomain.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    environment:
      - HOST=0.0.0.0
      - VITE_API_URL=https://mydomain.com/api
    restart: unless-stopped

volumes:
  pgdata:t: unless-stopped
